{% set name = "skill_tools" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - path: ../src
    folder: src
  - path: ../docs
    folder: docs
  - path: ../init.ils
  - path: ../readme.md

requirements:
  build:
    - python {{ python }}
    - setuptools
    - sphinx
    - recommonmark
    - sphinx_rtd_theme

about:
  home: https://github.com/skyworksinc/SKILL_Tools
  license: MIT
  summary: qub and qtest SKILL Librarigi
